name: App CI-CD

on:
  push:
    branches:
      - '*'

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Static Code Analysis
      run: docker run -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/src horuszup/horusec-cli:latest horusec start -p /src -P $(pwd)

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
    
    - name: Build & Push the Docker image
      run: |
        docker build . --file Dockerfile --tag app:${SHORT_SHA} --build-arg APP_VERSION=${SHORT_SHA} --build-arg API_KEY=${{ secrets.API_KEY }}
        docker tag app:${SHORT_SHA} glgacr.azurecr.io/app:${SHORT_SHA}
        docker tag app:${SHORT_SHA} glgacr.azurecr.io/app:latest
        docker login glgacr.azurecr.io --username ${{ secrets.ACR_USER }} --password ${{ secrets.ACR_TOKEN }}
        docker push glgacr.azurecr.io/app:${SHORT_SHA}
        docker push glgacr.azurecr.io/app:latest

  deploy_to_test:

    runs-on: ubuntu-latest

    needs: build

    steps:
    - uses: actions/checkout@v3

    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV    
  
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure - Update container app TEST
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az containerapp update --name catest --resource-group rg-dta --image glgacr.azurecr.io/app:${SHORT_SHA}

  deploy_to_prod:

    runs-on: ubuntu-latest

    needs: build

    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3

    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV    
  
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure - Update container app PROD
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az containerapp update --name caprod --resource-group rg-dta --image glgacr.azurecr.io/app:${SHORT_SHA}